Chore: swap goodtables to frictionless
qld-gov-au/ckanext-validation pull request #80
Opened 2024-12-28 03:25 UTC by duttonw

# Overview

Replace goodtables with frictionless library (per upstream)

Include backwards compatibility for basic goodtable options ['headers', 'skip_rows', 'delimiter'] to friction resource 'dialect' options.

Drop:
* goodtables==1.5.1 (11/10/2017
* datapackage==1.15.2 (24/2/2021) # pin to preserve compatibility with older tableschema
* validation-report.css that had goodtables css

Update to requirements:
* frictionless==5.18.0
* markupsafe
* jinja2<3.1
* tableschema

Needs scheming master (nothing cut above 3.0.0 at this time)
* https://github.com/ckan/ckanext-scheming.git@master

@ThrawnCA

2024-12-28 03:26 UTC, duttonw commented
another itch, was not as hard as it looked :)

2025-01-01 23:14 UTC, ThrawnCA requested changes
Mostly looks good, just a few minor things.

2025-01-01 23:14 UTC, ThrawnCA commented on ckanext/validation/templates/scheming/form_snippets/resource_schema.html
> +    {% asset 'ckanext-validation/resource-schema-form' %}
Other templates still use `include`, why is this different?

2025-01-01 23:14 UTC, ThrawnCA commented on ckanext/validation/tests/helpers.py
> +                "description": "Data reading error because of not supported or inconsistent contents.",
Probably should say "unsupported" rather than "not supported".

2025-01-01 23:32 UTC, duttonw commented on ckanext/validation/tests/helpers.py
> +                "description": "Data reading error because of not supported or inconsistent contents.",
This is exactly from the frictionless source base, can't change it. just here to 'mimic' real errors in mocks.

2025-01-01 23:38 UTC, ThrawnCA approved these changes

2025-01-01 23:47 UTC, duttonw commented on ckanext/validation/templates/scheming/form_snippets/resource_schema.html
> +    {% asset 'ckanext-validation/resource-schema-form' %}
aligned to upstream

2025-01-01 23:47 UTC, merged

2025-01-02 01:53 UTC, ThrawnCA commented on ckanext/validation/templates/scheming/form_snippets/resource_schema.html
> +    {% asset 'ckanext-validation/resource-schema-form' %}
This breaks `ckanext-data-qld` which still tries to `{% include 'validation/snippets/validation_resource-schema-form_' ~ type ~ '.html' %}`

2025-01-02 02:06 UTC, ThrawnCA commented on ckanext/validation/templates/scheming/form_snippets/resource_schema.html
> +    {% asset 'ckanext-validation/resource-schema-form' %}
For backwards compatibility, can we update the syntax here but retain `validation_resource-schema-form_asset.html`?

2025-01-02 02:25 UTC, ThrawnCA commented on ckanext/validation/templates/scheming/form_snippets/resource_schema.html
> +    {% asset 'ckanext-validation/resource-schema-form' %}
Raised https://github.com/qld-gov-au/ckanext-data-qld/pull/262 to adapt ckanext-data-qld to this.